<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Remotion.BuildScript</RootNamespace>
    <AssemblyName>Remotion.BuildScript.Nuke</AssemblyName>
    <NoWarn>CS0649</NoWarn>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>true</WarningsAsErrors>
  </PropertyGroup>

  <Import Project="..\Shared.build.props" />

  <ItemGroup>
    <None Include="..\license\Apache-2.0.licenseheader" Link="Apache-2.0.licenseheader"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CycloneDX.Utils" Version="8.0.3" />
    <PackageReference Include="Nuke.Build" Version="8.0.0" />
    <PackageReference Include="Nuke.Common" Version="8.0.0" />
    <PackageReference Include="Remotion.Infrastructure.SbomCleaner.Library" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BuildScript.Nuke.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CycloneDX" Version="4.0.0" ExcludeAssets="all" />
  </ItemGroup>

</Project>